apiVersion: apps/v1
kind: Deployment
metadata:
  name: dp-msv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dp-msv
  template:
    metadata:
      labels:
        app: dp-msv
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
        - name: dp-msv-ai
          image: curebigdata/dp_msv:v1.1
          volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          ports:
            - containerPort: 3000
          resources:
           limits:
             cpu: "4"
             nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: dp-msv
spec:
  # type: NodePort
  selector:
    app: dp-msv
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30006
