python main_for_bash.py \
--train \
--generate \
--count_threshold 2.0 \
--lookahead_degree 2 \
--img_size 512x512 \
--org_img_size 512 \
--data_folder ./input_data/cookie \
--num_samples 10 \
--variation_degree_schedule 1.0,0.98 \
--num_org_data 10 \
--prompt "A photo of ragdoll cat" \
--result_folder result/cookie \
--tmp_folder /tmp/cookie \
--api stable_diffusion \
--API_checkpoint 'runwayml/stable-diffusion-v1-5' \
--guidance_scale 7.5 \
--inference_steps 20 \
--API_batch_size 10 \
--epsilon 1.0 \
--num_samples_generate 2 \
--variation_degree 0.5 \