python pre_main.py \
--generate \
--count_threshold 2.0 \
--lookahead_degree 2 \
--img_size 512x512 \
--org_img_size 512 \
--data_folder /home/minsy/CUBIG/dp/data/cookie \
--num_samples_schedule 10,10 \
--variation_degree_schedule 1.0,0.98 \
--num_org_data 10 \
--initial_prompt "A photo of ragdoll cat" \
--result_folder result/cookie \
--tmp_folder /tmp/result/cookie \
--api stable_diffusion \
--random_sampling_checkpoint 'runwayml/stable-diffusion-v1-5' \
--random_sampling_guidance_scale 7.5 \
--random_sampling_num_inference_steps 20 \
--random_sampling_batch_size 10 \
--variation_checkpoint 'CompVis/stable-diffusion-v1-4' \
--variation_guidance_scale 7.5 \
--variation_num_inference_steps 20 \
--variation_batch_size 10 \
--epsilon 1.0 \
--num_samples 2 \
--variation_degree 0.5 \
--data_checkpoint_path /home/minsy/CUBIG/CUBIGate/result/cookie/1/_samples.npz 